/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditAccessRuleRouteImport } from './routes/edit-access-rule'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProposalsNewRouteImport } from './routes/proposals/new'
import { Route as ProposalsIdRouteImport } from './routes/proposals/$id'

const EditAccessRuleRoute = EditAccessRuleRouteImport.update({
  id: '/edit-access-rule',
  path: '/edit-access-rule',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsNewRoute = ProposalsNewRouteImport.update({
  id: '/proposals/new',
  path: '/proposals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsIdRoute = ProposalsIdRouteImport.update({
  id: '/proposals/$id',
  path: '/proposals/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/edit-access-rule': typeof EditAccessRuleRoute
  '/proposals/$id': typeof ProposalsIdRoute
  '/proposals/new': typeof ProposalsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/edit-access-rule': typeof EditAccessRuleRoute
  '/proposals/$id': typeof ProposalsIdRoute
  '/proposals/new': typeof ProposalsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/edit-access-rule': typeof EditAccessRuleRoute
  '/proposals/$id': typeof ProposalsIdRoute
  '/proposals/new': typeof ProposalsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-account'
    | '/edit-access-rule'
    | '/proposals/$id'
    | '/proposals/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-account'
    | '/edit-access-rule'
    | '/proposals/$id'
    | '/proposals/new'
  id:
    | '__root__'
    | '/'
    | '/create-account'
    | '/edit-access-rule'
    | '/proposals/$id'
    | '/proposals/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateAccountRoute: typeof CreateAccountRoute
  EditAccessRuleRoute: typeof EditAccessRuleRoute
  ProposalsIdRoute: typeof ProposalsIdRoute
  ProposalsNewRoute: typeof ProposalsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/edit-access-rule': {
      id: '/edit-access-rule'
      path: '/edit-access-rule'
      fullPath: '/edit-access-rule'
      preLoaderRoute: typeof EditAccessRuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/new': {
      id: '/proposals/new'
      path: '/proposals/new'
      fullPath: '/proposals/new'
      preLoaderRoute: typeof ProposalsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/$id': {
      id: '/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/proposals/$id'
      preLoaderRoute: typeof ProposalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateAccountRoute: CreateAccountRoute,
  EditAccessRuleRoute: EditAccessRuleRoute,
  ProposalsIdRoute: ProposalsIdRoute,
  ProposalsNewRoute: ProposalsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
